### ISSUE TITLE
Installing MUI 5 in the application

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/my-mui-cc#1]
Install MUI

**Comment by BigYusuf** [comment]
Hello

**Comment by BigYusuf** [comment]
To install and save in your package.json dependencies, run the command below using npm:

npm install @mui/material @emotion/react @emotion/styled

or Yarn

yarn add @mui/material @emotion/react @emotion/styled


Check this link out for more info
[https://mui.com/material-ui/getting-started/installation/](material ui installation guide)
